pipeline {
    agent any
    stages {
        stage('Database Container Setup') {
            steps {
                script {
                        sh 'docker rm -f mysql'
                        sh 'docker run -dt --name mysql1 -p 3306:3306 -e MYSQL_ROOT_PASSWORD=Abc@123 mysql:latest'
                    }
                }
            }
        stage('Backend Container Setup') {
            steps {
                script {
                    sh 'docker stop backend || true'
                    sh 'docker rm -f backend || true'
                    cd LMS-BE {
                            sh 'docker build -t backend .'
                            sh 'docker run -dt --name backend1 -p 8080:8080 --link mysql1:mysql backend'
                        } 
                    }
                }
            }
        }
    }
